server:
  ip: "localhost"
  zmq_port: 5555
  input_image: "pic/server/photo.bmp"

worker:
  output_dir: "pic/worker/"
  server_endpoint: "tcp://localhost:5555"
  postprocessor_endpoint: "tcp://localhost:5557"  # ← исправлено!

postprocessor:
  zmq_port: 5557
  output_dir: "pic/postProcessor/"
  processed_prefix: "proc_"
  bare_prefix: "bare_"
  max_frames: 250
  timeout_duration: 5000